# Generated by Django 6.0 on 2026-01-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_monthstory_id_alter_video_id_alter_video_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
    ]
