# Generated by Django 6.0 on 2026-01-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_remove_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.CharField(null=True),
        ),
    ]
