# Generated by Django 6.0 on 2026-01-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_video_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(null=True),
        ),
    ]
