# Generated by Django 6.0 on 2026-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daystory',
            name='datetime',
        ),
        migrations.AddField(
            model_name='daystory',
            name='day',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daystory',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daystory',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
