# Generated by Django 6.0 on 2026-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_first_start',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_photo_url',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(null=True),
        ),
    ]
